define INSERTION_INPUT
6
5 2 4 6 1 3
上記を入力をしてください
endef

export INSERTION_INPUT
insertion_sort:
	rustc insertion_sort.rs
	echo "$${INSERTION_INPUT}"
	./insertion_sort


define BUBBLE_INPUT
5
5 3 2 4 1
上記を入力をしてください
endef

export BUBBLE_INPUT
bubble_sort:
	rustc bubble_sort.rs
	echo "$${BUBBLE_INPUT}"
	./bubble_sort


define SELECTION_INPUT
6
5 6 4 2 1 3
上記を入力をしてください
endef

export SELECTION_INPUT
selection_sort:
	rustc selection_sort.rs
	echo "$${SELECTION_INPUT}"
	./selection_sort


define SHELL_INPUT
10
4 8 9 1 10 6 2 5 3 7
上記を入力をしてください
endef

export SHELL_INPUT
shell_sort:
	rustc shell_sort.rs
	echo "$${SHELL_INPUT}"
	./shell_sort